import { Phase2Placeholder } from '@/components/phase-2-placeholder';

export const metadata = { title: 'Planner' };

export default function PlannerPage() {
  return (
    <Phase2Placeholder
      title="Adaptive Study Planner"
      tagline="A plan that rewrites itself every day based on what you actually learned."
      whatsComing={[
        'Daily study schedule generated by the Orchestrator Agent from your mastery state.',
        'Automatic re-planning when you skip a day or discover a weak topic.',
        'Time-budget aware — tell it how many minutes you have and it fits the plan.',
        'Exports to calendar so the plan lives where you already work.',
      ]}
      parkedReason="The adaptive planner depends on a stable Orchestrator Agent with accurate strategy-mode output. Phase 1 proves strategy mode on Mentor first. Once strategy mode produces reliable recommendations, the planner is a straightforward multi-day extension — shipping it earlier would mean building on a moving target."
      targetPhase="Phase 2B"
    />
  );
}
