// ═══════════════════════════════════════════════════════════════
// PDF GENERATOR SERVICE
// Generate PDFs for notes, lectures, materials
// ═══════════════════════════════════════════════════════════════

import PDFDocument from 'pdfkit';
import fs from 'fs/promises';
import path from 'path';
import { createClient } from '@/lib/supabase/server';

export interface PDFOptions {
    title: string;
    content: string;
    author?: string;
    metadata?: Record<string, string>;
}

/**
 * Generate notes PDF
 */
export async function generateNotesPDF(options: PDFOptions): Promise<string> {
    const { title, content, author = 'UPSC CSE Master', metadata: _metadata = {} } = options;

    const doc = new PDFDocument({ size: 'A4', margin: 50 });

    const fileName = `notes_${Date.now()}.pdf`;
    const tempDir = path.join(process.cwd(), 'temp', 'pdfs');
    await fs.mkdir(tempDir, { recursive: true });

    const filePath = path.join(tempDir, fileName);
    const writeStream = require('fs').createWriteStream(filePath);

    doc.pipe(writeStream);

    // Header
    doc
        .fontSize(24)
        .text(title, { align: 'center' })
        .moveDown()
        .fontSize(10)
        .text(`Generated by ${author}`, { align: 'center' })
        .text(`Date: ${new Date().toLocaleDateString('en-IN')}`, { align: 'center' })
        .moveDown(2);

    // Content
    doc
        .fontSize(12)
        .text(content, {
            align: 'justify',
            lineGap: 5
        });

    // Footer
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i);
        doc
            .fontSize(8)
            .text(
                `Page ${i + 1} of ${pages.count}`,
                50,
                doc.page.height - 50,
                { align: 'center' }
            );
    }

    doc.end();

    await new Promise(resolve => writeStream.on('finish', resolve));

    // Upload to storage
    const supabase = await createClient();
    const pdfBuffer = await fs.readFile(filePath);

    const { error: uploadError } = await supabase.storage
        .from('notes')
        .upload(`pdfs/${fileName}`, pdfBuffer, {
            contentType: 'application/pdf'
        });

    if (uploadError) {
        throw new Error('PDF upload failed');
    }

    const { data: urlData } = supabase.storage
        .from('notes')
        .getPublicUrl(`pdfs/${fileName}`);

    // Cleanup
    await fs.unlink(filePath).catch(() => { });

    return urlData.publicUrl;
}

/**
 * Generate lecture notes PDF
 */
export async function generateLectureNotesPDF(
    lectureId: string,
    chapters: Array<{ number: number; title: string; content: string }>
): Promise<string> {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });

    const fileName = `lecture_${lectureId}.pdf`;
    const tempDir = path.join(process.cwd(), 'temp', 'pdfs');
    await fs.mkdir(tempDir, { recursive: true });

    const filePath = path.join(tempDir, fileName);
    const writeStream = require('fs').createWriteStream(filePath);

    doc.pipe(writeStream);

    // Title page
    doc
        .fontSize(28)
        .text('Lecture Notes', { align: 'center' })
        .moveDown(3);

    // Table of contents
    doc
        .fontSize(16)
        .text('Contents', { underline: true })
        .moveDown();

    chapters.forEach(ch => {
        doc.fontSize(12).text(`${ch.number}. ${ch.title}`);
    });

    doc.addPage();

    // Chapters
    chapters.forEach((chapter, idx) => {
        if (idx > 0) doc.addPage();

        doc
            .fontSize(18)
            .text(`Chapter ${chapter.number}: ${chapter.title}`, { underline: true })
            .moveDown()
            .fontSize(12)
            .text(chapter.content, { align: 'justify' });
    });

    doc.end();

    await new Promise(resolve => writeStream.on('finish', resolve));

    // Upload
    const supabase = await createClient();
    const pdfBuffer = await fs.readFile(filePath);

    const { error: _uploadError } = await supabase.storage
        .from('lectures')
        .upload(`notes/${fileName}`, pdfBuffer, {
            contentType: 'application/pdf'
        });

    const { data: urlData } = supabase.storage
        .from('lectures')
        .getPublicUrl(`notes/${fileName}`);

    await fs.unlink(filePath).catch(() => { });

    return urlData.publicUrl;
}

/**
 * Generate certificate
 */
export async function generateCertificate(
    userName: string,
    courseName: string
): Promise<string> {
    const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 50 });

    const fileName = `certificate_${Date.now()}.pdf`;
    const tempDir = path.join(process.cwd(), 'temp', 'pdfs');
    await fs.mkdir(tempDir, { recursive: true });

    const filePath = path.join(tempDir, fileName);
    const writeStream = require('fs').createWriteStream(filePath);

    doc.pipe(writeStream);

    // Certificate content
    doc
        .fontSize(40)
        .text('Certificate of Completion', { align: 'center' })
        .moveDown(2)
        .fontSize(16)
        .text('This certifies that', { align: 'center' })
        .moveDown()
        .fontSize(28)
        .text(userName, { align: 'center', underline: true })
        .moveDown()
        .fontSize(16)
        .text('has successfully completed', { align: 'center' })
        .moveDown()
        .fontSize(24)
        .text(courseName, { align: 'center' })
        .moveDown(2)
        .fontSize(12)
        .text(`Date: ${new Date().toLocaleDateString('en-IN')}`, { align: 'center' });

    doc.end();

    await new Promise(resolve => writeStream.on('finish', resolve));

    const supabase = await createClient();
    const pdfBuffer = await fs.readFile(filePath);

    const { error: _certUploadError } = await supabase.storage
        .from('certificates')
        .upload(fileName, pdfBuffer, {
            contentType: 'application/pdf'
        });

    const { data: urlData } = supabase.storage
        .from('certificates')
        .getPublicUrl(fileName);

    await fs.unlink(filePath).catch(() => { });

    return urlData.publicUrl;
}